CREATE TABLE CHANNEL (
	UUID varchar(100) NOT NULL,
	NAME varchar(200) NOT NULL,
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL,
	UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NULL,
	PRIMARY KEY(UUID)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci;
