CREATE TABLE NOTIFICATION (
	UUID varchar(100) NOT NULL,
	CHANNEL_UUID varchar(100) NOT NULL,
	SUBJECT varchar(200) NULL,
	SENDER varchar(200) NOT NULL,
	RECEIVER varchar(200) NOT NULL,
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL,
	UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NULL,
	PRIMARY KEY (UUID)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci;

ALTER TABLE NOTIFICATION ADD CONSTRAINT NOTIFICATION_FK FOREIGN KEY (CHANNEL_UUID) REFERENCES CHANNEL(UUID);
