CREATE TABLE CONFIG_SMTP (
	CHANNEL_UUID varchar(100) NOT NULL,
	HOST varchar(500) NOT NULL,
	PORT INT NOT NULL,
	USERNAME TIMESTAMP NOT NULL,
	PASSWORD varchar(200) NULL,
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL,
	UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NULL,
	PRIMARY KEY (CHANNEL_UUID)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci;

ALTER TABLE CONFIG_SMTP ADD CONSTRAINT CONFIG_SMTP_FK FOREIGN KEY (CHANNEL_UUID) REFERENCES CHANNEL(UUID);
